---
title: "figure6"
author: "Mette Ludwig"
date: "2022-10-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r}
library(openxlsx)
library(plotrix)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(cowplot)
library(reshape2)
library(emmeans)
```

# Load peripheral data
```{r}
blood <- read.xlsx("/projects/mludwig/hippo_GLP1/data/in_vivo/sc_blood_measurements.xlsx")
```

# Figure 6
```{r}
# TNFa
TNFa <- blood[which(blood$time != "11d"), c("treatment", "drug", "time", "Tnfa")]
colnames(TNFa)[4] <- "TNFa"
TNFa <- TNFa[!is.na(TNFa$TNFa),]
TNFa$drug <- factor(TNFa$drug, levels = c("Veh-PBS", "Veh-LPS", "Sema-LPS")) 
TNFa$time <- factor(TNFa$time, levels = c("2h", "24h", "5d")) 

# Compute statistics
# Linear model
model <- lm(TNFa ~ drug * time, data=TNFa)

# Least-squares means
model <- lsmeans(model, pairwise ~ drug | time, adjust = "fdr")
model <- test(model$contrasts)

p.adj <- c(model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][1], 
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][1],
           model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][2],
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][2])
p.symbol <- rep("NS", 4) 
p.symbol[which(p.adj <= 0.05)] <- "*"
p.symbol[which(p.adj <= 0.01)] <- "**"
p.symbol[which(p.adj <= 0.001)] <- "***"

TNFa <- TNFa[which(TNFa$time %in% c("2h", "24h")),]
TNFa$treatment <- factor(TNFa$treatment, levels = c("Veh-PBS-2h", "Veh-LPS-2h", "Sema-LPS-2h",
                                                    "Veh-PBS-24h", "Veh-LPS-24h", "Sema-LPS-24h"))

asterisk.position <- c(rep(max(TNFa$TNFa[which(TNFa$time == "2h")]), 2),
                       rep(max(TNFa$TNFa[which(TNFa$time == "24h")]), 2))


# Mean and SEM
TNFa.summary <- aggregate(TNFa[, c("TNFa"), drop = F],
                          by = list(TNFa$treatment), FUN = mean, na.rm = T)
colnames(TNFa.summary) <- c("treatment", "mean")
TNFa.summary$SEM <- aggregate(TNFa[, c("TNFa"), drop = F], 
                              by = list(TNFa$treatment), 
                              FUN = std.error, na.rm = T)$TNFa
TNFa.summary$title <- paste0("TNF", "\u03b1")

# Plot
pal <- rep(c("#33CC66", "#336666", "#A60FA6"), 2)
TNFa.plot <- ggplot(TNFa.summary, aes(x = treatment, y = mean, fill = treatment)) +
  facet_wrap(~title, ncol = 1) +
  geom_bar(stat = "identity", position="dodge", color = "black", width = 0.7, size = 0.3) +
  geom_point(data = TNFa, aes(x = treatment, y = TNFa),
             size = 0.2, position = position_jitter(w = 0.05, height = 0, seed = 1)) +
  geom_errorbar(data = TNFa.summary, aes(ymin = mean, ymax = mean+SEM), width = 0.5, 
                position=position_dodge(0.7), size = 0.3) +
  xlab("") + ylab(paste0(TNFa.summary$title, (" (pg/ml)"))) +
  theme_pubr() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black", size = 0.4),
        axis.text.x = element_text(size=6, face="bold", angle=45, hjust=1),
        axis.text.y = element_text(size=6, face="bold"),
        axis.title.x = element_text(size=6, face="bold"),
        axis.title.y = element_text(size=6, face="bold",
                                    margin=unit(c(0,0,0,0), "cm")),
        # margin: top, right, bottom, and left
        plot.margin = unit(c(0, 0, 0, 0.1), "cm"),
        legend.position = "none",
        strip.text = element_text(size=6, face="bold")) +
  scale_fill_manual(values = pal) + 
  scale_y_continuous(breaks = seq(0, 2500, 500), limits = c(0, 2500)) +
  geom_signif(y_position = asterisk.position + 100, xmin = c(1, 2.01, 4, 5.01),
  xmax = c(1.99, 3, 4.99, 6), tip_length = 0.01,
  fontface = "bold", vjust = 0.2,
  annotation = p.symbol,
  size = 0.2, textsize = 1.55)

TNFa.plot
```

```{r}
# INFg
INFg <- blood[which(blood$time != "11d"), c("treatment", "drug", "time", "Infg")]
colnames(INFg)[4] <- "INFg"
INFg <- INFg[!is.na(INFg$INFg),]
INFg$drug <- factor(INFg$drug, levels = c("Veh-PBS", "Veh-LPS", "Sema-LPS")) 
INFg$time <- factor(INFg$time, levels = c("2h", "24h", "5d")) 

# Compute statistics
# Linear model
model <- lm(INFg ~ drug * time, data=INFg)

# Least-squares means
model <- lsmeans(model, pairwise ~ drug | time, adjust = "fdr")
model <- test(model$contrasts)

p.adj <- c(model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][1], 
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][1],
           model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][2],
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][2])
p.symbol <- rep("NS", 4)  
p.symbol[which(p.adj <= 0.05)] <- "*"
p.symbol[which(p.adj <= 0.01)] <- "**"
p.symbol[which(p.adj <= 0.001)] <- "***"

INFg <- INFg[which(INFg$time %in% c("2h", "24h")),]
INFg$treatment <- factor(INFg$treatment, levels = c("Veh-PBS-2h", "Veh-LPS-2h", "Sema-LPS-2h",
                                                    "Veh-PBS-24h", "Veh-LPS-24h", "Sema-LPS-24h"))
asterisk.position <- c(rep(max(INFg$INFg[which(INFg$time == "2h")]), 2),
                       rep(max(INFg$INFg[which(INFg$time == "24h")]), 2))


# Mean and SEM
INFg.summary <- aggregate(INFg[, c("INFg"), drop = F],
                          by = list(INFg$treatment), FUN = mean, na.rm = T)
colnames(INFg.summary) <- c("treatment", "mean")
INFg.summary$SEM <- aggregate(INFg[, c("INFg"), drop = F], 
                              by = list(INFg$treatment), 
                              FUN = std.error, na.rm = T)$INFg
INFg.summary$title <- paste0("INF", "\u03b3")

# Plot
pal <- rep(c("#33CC66", "#336666", "#A60FA6"), 2)
INFg.plot <- ggplot(INFg.summary, aes(x = treatment, y = mean, fill = treatment)) +
  facet_wrap(~title, ncol = 1) +
  geom_bar(stat = "identity", position="dodge", color = "black", width = 0.7, size = 0.3) +
  geom_point(data = INFg, aes(x = treatment, y = INFg),
             size = 0.2, position = position_jitter(w = 0.05, height = 0, seed = 1)) +
  geom_errorbar(data = INFg.summary, aes(ymin = mean, ymax = mean+SEM), width = 0.5, 
                position=position_dodge(0.7), size = 0.3) +
  xlab("") + ylab(paste0(INFg.summary$title, (" (pg/ml)"))) +
  theme_pubr() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black", size = 0.4),
        axis.text.x = element_text(size=6, face="bold", angle=45, hjust=1),
        axis.text.y = element_text(size=6, face="bold"),
        axis.title.x = element_text(size=6, face="bold"),
        axis.title.y = element_text(size=6, face="bold",
                                    margin=unit(c(0,0,0,0), "cm")),
        # margin: top, right, bottom, and left
        plot.margin = unit(c(0, 0, 0, 0.1), "cm"),
        legend.position = "none",
        strip.text = element_text(size=6, face="bold")) +
  scale_fill_manual(values = pal) + 
  scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0, 10)) +
  geom_signif(y_position = asterisk.position + 0.4, xmin = c(1, 2.01, 4, 5.01),
  xmax = c(1.99, 3, 4.99, 6), tip_length = 0.01,
  fontface = "bold", vjust = 0.2,
  annotation = p.symbol,
  size = 0.2, textsize = 1.55)

INFg.plot
```


```{r}
# IL-1b
IL1b <- blood[which(blood$time != "11d"), c("treatment", "drug", "time", "Il1b")]
colnames(IL1b)[4] <- "IL1b"
IL1b <- IL1b[!is.na(IL1b$IL1b),]
IL1b$drug <- factor(IL1b$drug, levels = c("Veh-PBS", "Veh-LPS", "Sema-LPS")) 
IL1b$time <- factor(IL1b$time, levels = c("2h", "24h", "5d")) 

# Compute statistics
# Linear model
model <- lm(IL1b ~ drug * time, data=IL1b)

# Least-squares means
model <- lsmeans(model, pairwise ~ drug | time, adjust = "fdr")
model <- test(model$contrasts)

p.adj <- c(model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][1], 
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][1],
           model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][2],
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][2])
p.symbol <- rep("NS", 4)  
p.symbol[which(p.adj <= 0.05)] <- "*"
p.symbol[which(p.adj <= 0.01)] <- "**"
p.symbol[which(p.adj <= 0.001)] <- "***"

IL1b <- IL1b[which(IL1b$time %in% c("2h", "24h")),]
IL1b$treatment <- factor(IL1b$treatment, levels = c("Veh-PBS-2h", "Veh-LPS-2h", "Sema-LPS-2h",
                                                    "Veh-PBS-24h", "Veh-LPS-24h", "Sema-LPS-24h"))
asterisk.position <- c(rep(max(IL1b$IL1b[which(IL1b$time == "2h")]), 2),
                       rep(max(IL1b$IL1b[which(IL1b$time == "24h")]), 2))


# Mean and SEM
IL1b.summary <- aggregate(IL1b[, c("IL1b"), drop = F],
                          by = list(IL1b$treatment), FUN = mean, na.rm = T)
colnames(IL1b.summary) <- c("treatment", "mean")
IL1b.summary$SEM <- aggregate(IL1b[, c("IL1b"), drop = F], 
                              by = list(IL1b$treatment), 
                              FUN = std.error, na.rm = T)$IL1b
IL1b.summary$title <- paste0("IL-1", "\u03b2")

# Plot
pal <- rep(c("#33CC66", "#336666", "#A60FA6"), 2)
IL1b.plot <- ggplot(IL1b.summary, aes(x = treatment, y = mean, fill = treatment)) +
  facet_wrap(~title, ncol = 1) +
  geom_bar(stat = "identity", position="dodge", color = "black", width = 0.7, size = 0.3) +
  geom_point(data = IL1b, aes(x = treatment, y = IL1b),
             size = 0.2, position = position_jitter(w = 0.05, height = 0, seed = 1)) +
  geom_errorbar(data = IL1b.summary, aes(ymin = mean, ymax = mean+SEM), width = 0.5, 
                position=position_dodge(0.7), size = 0.3) +
  xlab("") + ylab(paste0(IL1b.summary$title, (" (pg/ml)"))) +
  theme_pubr() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black", size = 0.4),
        axis.text.x = element_text(size=6, face="bold", angle=45, hjust=1),
        axis.text.y = element_text(size=6, face="bold"),
        axis.title.x = element_text(size=6, face="bold"),
        axis.title.y = element_text(size=6, face="bold",
                                    margin=unit(c(0,0,0,0), "cm")),
        # margin: top, right, bottom, and left
        plot.margin = unit(c(0, 0, 0, 0.1), "cm"),
        legend.position = "none",
        strip.text = element_text(size=6, face="bold")) +
  scale_fill_manual(values = pal) + 
  scale_y_continuous(breaks = seq(0, 65, 20), limits = c(0, 68)) +
  geom_signif(y_position = asterisk.position[c(1,2,4)] + 2, xmin = c(1, 2.01, 4),
  xmax = c(1.99, 3, 4.99), tip_length = 0.01,
  fontface = "bold", vjust = 0.2,
  annotation = p.symbol[c(1,2,4)],
  size = 0.2, textsize = 1.55)

IL1b.plot
```

```{r}
# IL-5
IL5 <- blood[which(blood$time != "11d"), c("treatment", "drug", "time", "Il5")]
colnames(IL5)[4] <- "IL5"
IL5 <- IL5[!is.na(IL5$IL5),]
IL5$drug <- factor(IL5$drug, levels = c("Veh-PBS", "Veh-LPS", "Sema-LPS")) 
IL5$time <- factor(IL5$time, levels = c("2h", "24h", "5d")) 

# Compute statistics
# Linear model
model <- lm(IL5 ~ drug * time, data=IL5)

# Least-squares means
model <- lsmeans(model, pairwise ~ drug | time, adjust = "fdr")
model <- test(model$contrasts)

p.adj <- c(model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][1], 
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][1],
           model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][2],
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][2])
p.symbol <- rep("NS", 4)  
p.symbol[which(p.adj <= 0.05)] <- "*"
p.symbol[which(p.adj <= 0.01)] <- "**"
p.symbol[which(p.adj <= 0.001)] <- "***"

IL5 <- IL5[which(IL5$time %in% c("2h", "24h")),]
IL5$treatment <- factor(IL5$treatment, levels = c("Veh-PBS-2h", "Veh-LPS-2h", "Sema-LPS-2h",
                                                    "Veh-PBS-24h", "Veh-LPS-24h", "Sema-LPS-24h"))
asterisk.position <- c(rep(max(IL5$IL5[which(IL5$time == "2h")]), 2),
                       rep(max(IL5$IL5[which(IL5$time == "24h")]), 2))


# Mean and SEM
IL5.summary <- aggregate(IL5[, c("IL5"), drop = F],
                          by = list(IL5$treatment), FUN = mean, na.rm = T)
colnames(IL5.summary) <- c("treatment", "mean")
IL5.summary$SEM <- aggregate(IL5[, c("IL5"), drop = F], 
                              by = list(IL5$treatment), 
                              FUN = std.error, na.rm = T)$IL5
IL5.summary$title <- "IL-5"

# Plot
pal <- rep(c("#33CC66", "#336666", "#A60FA6"), 2)
IL5.plot <- ggplot(IL5.summary, aes(x = treatment, y = mean, fill = treatment)) +
  facet_wrap(~title, ncol = 1) +
  geom_bar(stat = "identity", position="dodge", color = "black", width = 0.7, size = 0.3) +
  geom_point(data = IL5, aes(x = treatment, y = IL5),
             size = 0.2, position = position_jitter(w = 0.05, height = 0, seed = 1)) +
  geom_errorbar(data = IL5.summary, aes(ymin = mean, ymax = mean+SEM), width = 0.5, 
                position=position_dodge(0.7), size = 0.3) +
  xlab("") + ylab(paste0(IL5.summary$title, (" (pg/ml)"))) +
  theme_pubr() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black", size = 0.4),
        axis.text.x = element_text(size=6, face="bold", angle=45, hjust=1),
        axis.text.y = element_text(size=6, face="bold"),
        axis.title.x = element_text(size=6, face="bold"),
        axis.title.y = element_text(size=6, face="bold",
                                    margin=unit(c(0,0,0,0), "cm")),
        # margin: top, right, bottom, and left
        plot.margin = unit(c(0, 0, 0, 0.1), "cm"),
        legend.position = "none",
        strip.text = element_text(size=6, face="bold")) +
  scale_fill_manual(values = pal) + 
  scale_y_continuous(breaks = seq(0, 20, 5), limits = c(0, 18)) +
  geom_signif(y_position = asterisk.position + 0.8, xmin = c(1, 2.01, 4, 5.01),
  xmax = c(1.99, 3, 4.99, 6), tip_length = 0.01,
  fontface = "bold", vjust = 0.2,
  annotation = p.symbol,
  size = 0.2, textsize = 1.55)

IL5.plot
```

```{r}
# IL-6
options(scipen=10000)
IL6 <- blood[which(blood$time != "11d"), c("treatment", "drug", "time", "Il6")]
colnames(IL6)[4] <- "IL6"
IL6 <- IL6[!is.na(IL6$IL6),]
IL6$drug <- factor(IL6$drug, levels = c("Veh-PBS", "Veh-LPS", "Sema-LPS")) 
IL6$time <- factor(IL6$time, levels = c("2h", "24h", "5d")) 

# Compute statistics
# Linear model
model <- lm(IL6 ~ drug * time, data=IL6)

# Least-squares means
model <- lsmeans(model, pairwise ~ drug | time, adjust = "fdr")
model <- test(model$contrasts)

p.adj <- c(model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][1], 
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][1],
           model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][2],
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][2])
p.symbol <- rep("NS", 4)  
p.symbol[which(p.adj <= 0.05)] <- "*"
p.symbol[which(p.adj <= 0.01)] <- "**"
p.symbol[which(p.adj <= 0.001)] <- "***"

IL6 <- IL6[which(IL6$time %in% c("2h", "24h")),]
IL6$treatment <- factor(IL6$treatment, levels = c("Veh-PBS-2h", "Veh-LPS-2h", "Sema-LPS-2h",
                                                    "Veh-PBS-24h", "Veh-LPS-24h", "Sema-LPS-24h"))
asterisk.position <- c(rep(max(IL6$IL6[which(IL6$time == "2h")]), 2),
                       rep(max(IL6$IL6[which(IL6$time == "24h")]), 2))


# Mean and SEM
IL6.summary <- aggregate(IL6[, c("IL6"), drop = F],
                          by = list(IL6$treatment), FUN = mean, na.rm = T)
colnames(IL6.summary) <- c("treatment", "mean")
IL6.summary$SEM <- aggregate(IL6[, c("IL6"), drop = F], 
                              by = list(IL6$treatment), 
                              FUN = std.error, na.rm = T)$IL6
IL6.summary$title <- "IL-6"

# Plot
pal <- rep(c("#33CC66", "#336666", "#A60FA6"), 2)
IL6.plot <- ggplot(IL6.summary, aes(x = treatment, y = mean, fill = treatment)) +
  facet_wrap(~title, ncol = 1) +
  geom_bar(stat = "identity", position="dodge", color = "black", width = 0.7, size = 0.3) +
  geom_point(data = IL6, aes(x = treatment, y = IL6),
             size = 0.2, position = position_jitter(w = 0.05, height = 0, seed = 1)) +
  geom_errorbar(data = IL6.summary, aes(ymin = mean, ymax = mean+SEM), width = 0.5, 
                position=position_dodge(0.7), size = 0.3) +
  xlab("") + ylab(paste0(IL6.summary$title, (" (pg/ml)"))) +
  theme_pubr() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black", size = 0.4),
        axis.text.x = element_text(size=6, face="bold", angle=45, hjust=1),
        axis.text.y = element_text(size=6, face="bold"),
        axis.title.x = element_text(size=6, face="bold"),
        axis.title.y = element_text(size=6, face="bold",
                                    margin=unit(c(0,0,0,0), "cm")),
        # margin: top, right, bottom, and left
        plot.margin = unit(c(0, 0, 0, 0.1), "cm"),
        legend.position = "none",
        strip.text = element_text(size=6, face="bold")) +
  scale_fill_manual(values = pal) + 
  scale_y_continuous(breaks = seq(0, 100000, 20000), limits = c(0, 112000)) +
  geom_signif(y_position = asterisk.position + 4000, xmin = c(1, 2.01, 4, 5.01),
  xmax = c(1.99, 3, 4.99, 6), tip_length = 0.01,
  fontface = "bold", vjust = 0.2,
  annotation = p.symbol,
  size = 0.2, textsize = 1.55)

IL6.plot
```

```{r}
# CXCL1
CXCL1 <- blood[which(blood$time != "11d"), c("treatment", "drug", "time", "Cxcl1")]
colnames(CXCL1)[4] <- "CXCL1"
CXCL1 <- CXCL1[!is.na(CXCL1$CXCL1),]
CXCL1$drug <- factor(CXCL1$drug, levels = c("Veh-PBS", "Veh-LPS", "Sema-LPS")) 
CXCL1$time <- factor(CXCL1$time, levels = c("2h", "24h", "5d")) 

# Compute statistics
# Linear model
model <- lm(CXCL1 ~ drug * time, data=CXCL1)

# Least-squares means
model <- lsmeans(model, pairwise ~ drug | time, adjust = "fdr")
model <- test(model$contrasts)

p.adj <- c(model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][1], 
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][1],
           model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][2],
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][2])
p.symbol <- rep("NS", 4)  
p.symbol[which(p.adj <= 0.05)] <- "*"
p.symbol[which(p.adj <= 0.01)] <- "**"
p.symbol[which(p.adj <= 0.001)] <- "***"

CXCL1 <- CXCL1[which(CXCL1$time %in% c("2h", "24h")),]
CXCL1$treatment <- factor(CXCL1$treatment, levels = c("Veh-PBS-2h", "Veh-LPS-2h", "Sema-LPS-2h",
                                                    "Veh-PBS-24h", "Veh-LPS-24h", "Sema-LPS-24h"))
asterisk.position <- c(rep(max(CXCL1$CXCL1[which(CXCL1$time == "2h")]), 2),
                       rep(max(CXCL1$CXCL1[which(CXCL1$time == "24h")]), 2))


# Mean and SEM
CXCL1.summary <- aggregate(CXCL1[, c("CXCL1"), drop = F],
                          by = list(CXCL1$treatment), FUN = mean, na.rm = T)
colnames(CXCL1.summary) <- c("treatment", "mean")
CXCL1.summary$SEM <- aggregate(CXCL1[, c("CXCL1"), drop = F], 
                              by = list(CXCL1$treatment), 
                              FUN = std.error, na.rm = T)$CXCL1
CXCL1.summary$title <- "CXCL1"

# Plot
pal <- rep(c("#33CC66", "#336666", "#A60FA6"), 2)
CXCL1.plot <- ggplot(CXCL1.summary, aes(x = treatment, y = mean, fill = treatment)) +
  facet_wrap(~title, ncol = 1) +
  geom_bar(stat = "identity", position="dodge", color = "black", width = 0.7, size = 0.3) +
  geom_point(data = CXCL1, aes(x = treatment, y = CXCL1),
             size = 0.2, position = position_jitter(w = 0.05, height = 0, seed = 1)) +
  geom_errorbar(data = CXCL1.summary, aes(ymin = mean, ymax = mean+SEM), width = 0.5, 
                position=position_dodge(0.7), size = 0.3) +
  xlab("") + ylab(paste0(CXCL1.summary$title, (" (pg/ml)"))) +
  theme_pubr() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black", size = 0.4),
        axis.text.x = element_text(size=6, face="bold", angle=45, hjust=1),
        axis.text.y = element_text(size=6, face="bold"),
        axis.title.x = element_text(size=6, face="bold"),
        axis.title.y = element_text(size=6, face="bold",
                                    margin=unit(c(0,0,0,0), "cm")),
        # margin: top, right, bottom, and left
        plot.margin = unit(c(0, 0, 0, 0.1), "cm"),
        legend.position = "none",
        strip.text = element_text(size=6, face="bold")) +
  scale_fill_manual(values = pal) + 
  scale_y_continuous(breaks = seq(0, 75000, 25000), limits = c(0, 80000)) +
  geom_signif(y_position = asterisk.position + 4000, xmin = c(1, 2.01, 4, 5.01),
  xmax = c(1.99, 3, 4.99, 6), tip_length = 0.01,
  fontface = "bold", vjust = 0.2,
  annotation = p.symbol,
  size = 0.2, textsize = 1.55)

CXCL1.plot
```

```{r}
# IL-10
IL10 <- blood[which(blood$time != "11d"), c("treatment", "drug", "time", "Il10")]
colnames(IL10)[4] <- "IL10"
IL10 <- IL10[!is.na(IL10$IL10),]
IL10$drug <- factor(IL10$drug, levels = c("Veh-PBS", "Veh-LPS", "Sema-LPS")) 
IL10$time <- factor(IL10$time, levels = c("2h", "24h", "5d")) 

# Compute statistics
# Linear model
model <- lm(IL10 ~ drug * time, data=IL10)

# Least-squares means
model <- lsmeans(model, pairwise ~ drug | time, adjust = "fdr")
model <- test(model$contrasts)

p.adj <- c(model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][1], 
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][1],
           model$p.value[which(model$contrast == "(Veh-PBS) - (Veh-LPS)")][2],
           model$p.value[which(model$contrast == "(Veh-LPS) - (Sema-LPS)")][2])
p.symbol <- rep("NS", 4)  
p.symbol[which(p.adj <= 0.05)] <- "*"
p.symbol[which(p.adj <= 0.01)] <- "**"
p.symbol[which(p.adj <= 0.001)] <- "***"

IL10 <- IL10[which(IL10$time %in% c("2h", "24h")),]
IL10$treatment <- factor(IL10$treatment, levels = c("Veh-PBS-2h", "Veh-LPS-2h", "Sema-LPS-2h",
                                                    "Veh-PBS-24h", "Veh-LPS-24h", "Sema-LPS-24h"))
asterisk.position <- c(rep(max(IL10$IL10[which(IL10$time == "2h")]), 2),
                       rep(max(IL10$IL10[which(IL10$time == "24h")]), 2))


# Mean and SEM
IL10.summary <- aggregate(IL10[, c("IL10"), drop = F],
                          by = list(IL10$treatment), FUN = mean, na.rm = T)
colnames(IL10.summary) <- c("treatment", "mean")
IL10.summary$SEM <- aggregate(IL10[, c("IL10"), drop = F], 
                              by = list(IL10$treatment), 
                              FUN = std.error, na.rm = T)$IL10
IL10.summary$title <- "IL-10"

# Plot
pal <- rep(c("#33CC66", "#336666", "#A60FA6"), 2)
IL10.plot <- ggplot(IL10.summary, aes(x = treatment, y = mean, fill = treatment)) +
  facet_wrap(~title, ncol = 1) +
  geom_bar(stat = "identity", position="dodge", color = "black", width = 0.7, size = 0.3) +
  geom_point(data = IL10, aes(x = treatment, y = IL10),
             size = 0.2, position = position_jitter(w = 0.05, height = 0, seed = 1)) +
  geom_errorbar(data = IL10.summary, aes(ymin = mean, ymax = mean+SEM), width = 0.5, 
                position=position_dodge(0.7), size = 0.3) +
  xlab("") + ylab(paste0(IL10.summary$title, (" (pg/ml)"))) +
  theme_pubr() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black", size = 0.4),
        axis.text.x = element_text(size=6, face="bold", angle=45, hjust=1),
        axis.text.y = element_text(size=6, face="bold"),
        axis.title.x = element_text(size=6, face="bold"),
        axis.title.y = element_text(size=6, face="bold",
                                    margin=unit(c(0,0,0,0), "cm")),
        # margin: top, right, bottom, and left
        plot.margin = unit(c(0, 0, 0, 0.1), "cm"),
        legend.position = "none",
        strip.text = element_text(size=6, face="bold")) +
  scale_fill_manual(values = pal) + 
  scale_y_continuous(breaks = seq(0, 6000, 2000), limits = c(0, 7000)) +
  geom_signif(y_position = asterisk.position + 200, xmin = c(1, 2.01, 4, 5.01),
  xmax = c(1.99, 3, 4.99, 6), tip_length = 0.01,
  fontface = "bold", vjust = 0.2,
  annotation = p.symbol,
  size = 0.2, textsize = 1.55)

IL10.plot
```

# Combine all plots
```{r}
fig6 <- plot_grid(TNFa.plot, INFg.plot, IL1b.plot, IL5.plot, 
                   IL6.plot, CXCL1.plot, IL10.plot,
                   ncol = 7, align = "h", axis = "tb",                   
                   rel_widths = c(1, 1, 1, 1, 1, 1, 1)) 


ggsave("/projects/mludwig/hippo_GLP1/output/figures/figure6.png", fig6, height = 60, width = 183,
       units = "mm")
```