---
title: "figure2"
author: "Mette Ludwig"
date: "2022-10-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r}
library(Seurat)
library(miloR)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(dplyr)
library(SingleCellExperiment)
library(scater)
library(scran)
library(patchwork)
library(RColorBrewer)
library(cowplot)
```

# Load Seurat objects
```{r}
hippo.glia <- readRDS("/projects/mludwig/hippo_GLP1/output/Seurat_objs/hippo_glia_Seurat_obj_labels.rds")
hippo.neurons <- readRDS("/projects/mludwig/hippo_GLP1/output/Seurat_objs/hippo_neurons_Seurat_obj_labels.rds")
```

# Load milo objects
```{r}
hippo.glia.veh.milo <- readRDS("/projects/mludwig/hippo_GLP1/output/milo_objs/hippo_glia_veh_milo_obj.rds")
hippo.glia.LPS.milo <- readRDS("/projects/mludwig/hippo_GLP1/output/milo_objs/hippo_glia_LPS_milo_obj.rds")

hippo.neurons.veh.milo <- readRDS("/projects/mludwig/hippo_GLP1/output/milo_objs/hippo_neurons_veh_milo_obj.rds")
hippo.neurons.LPS.milo <- readRDS("/projects/mludwig/hippo_GLP1/output/milo_objs/hippo_neurons_LPS_milo_obj.rds")
```

# Figure 2c
```{r}
# UMAP of hippocampal glial cells
umap.embed.glia <- as.data.frame(hippo.glia@reductions$umap@cell.embeddings)
umap.embed.glia$cell.type <- hippo.glia$cell.type2
label <- data.frame(cell.type = unique(hippo.glia$cell.type))
label <- umap.embed.glia %>% 
  dplyr::group_by(cell.type) %>% 
  dplyr::summarize(x = median(UMAP_1), y = median(UMAP_2)) 

# Plot
set.seed(15)
n.cols <- length(unique(hippo.glia$cell.type2))
pal <- colorRampPalette(brewer.pal(12, "Accent"))(n.cols)
pal <- sample(pal)

umap.glia.plot <- ggplot(data = umap.embed.glia, mapping = aes(x = UMAP_1, y = UMAP_2, 
                                                           colour = cell.type)) +
  geom_point(size = 0.1, alpha = 0.5) +
  theme_pubr() +
  theme(axis.line = element_line(colour = "black", size = 0.3),
        axis.ticks = element_line(colour = "black", size = 0.3),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.position = "None",
        axis.title = element_text(size=6, face="bold"),
        axis.text = element_text(size=6, face="bold")) + 
  xlab("UMAP 1") + ylab("UMAP 2") + 
  scale_color_manual(values = pal) +
  geom_text_repel(data = label, aes(label = cell.type, x=x, y=y), 
                  size=2, fontface="bold", inherit.aes = F) 
umap.glia.plot
```

# Figure 2d
```{r}
# UMAP of hippocampal neurons
umap.embed.neurons <- as.data.frame(hippo.neurons@reductions$umap@cell.embeddings)
umap.embed.neurons$cell.type <- hippo.neurons$cell.type2
label <- data.frame(cell.type = unique(umap.embed.neurons$cell.type))
label <- umap.embed.neurons %>% 
  dplyr::group_by(cell.type) %>% 
  dplyr::summarize(x = median(UMAP_1), y = median(UMAP_2)) 

# Plot
set.seed(2)
n.cols <- length(unique(hippo.neurons$cell.type2))
pal <- colorRampPalette(brewer.pal(12, "Accent"))(n.cols)
pal <- sample(pal)

umap.neurons.plot <- ggplot(data = umap.embed.neurons, mapping = aes(x = UMAP_1, y = UMAP_2, 
                                                           colour = cell.type)) +
  geom_point(size = 0.1, alpha = 0.5) +
  theme_pubr() +
  theme(axis.line = element_line(colour = "black", size = 0.3),
        axis.ticks = element_line(colour = "black", size = 0.3),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        legend.position = "None",
        axis.title = element_text(size=6, face="bold"),
        axis.text = element_text(size=6, face="bold")) + 
  xlab("UMAP 1") + ylab("UMAP 2") + 
  scale_color_manual(values = pal) +
  geom_text_repel(data = label, aes(label = cell.type, x=x, y=y), 
                  size=2, fontface="bold", inherit.aes = F) 
umap.neurons.plot
```
# Figure 2e
```{r}
# Milo plot of hippocampal glial cells
# Defining experimental design
design <- data.frame(colData(hippo.glia.veh.milo))[, c("hash.ID", "drug", "time")]
design <- distinct(design)
design$drug <- factor(design$drug, levels = c("Veh-PBS", "Veh-LPS"))
rownames(design) <- design$hash.ID

# Testing
model <- model.matrix(~ drug, data = design)
colnames(model) <- make.names(colnames(model))
da.results.glia.veh <- testNhoods(hippo.glia.veh.milo, design = model, design.df = design, model.contrasts = "drugVeh.LPS")

da.results.glia.veh %>% arrange(PValue) %>% head(n = 50)
length(which(da.results.glia.veh$SpatialFDR < 0.05))

# Plot neighborhood graph
milo.umap.glia.plot <- plotNhoodGraphDA(hippo.glia.veh.milo, da.results.glia.veh, layout = "UMAP", alpha = 0.05, 
                              res_column = "logFC", size=2) +
  theme_pubr() +
  guides(size="none", edge_width="none", fill = guide_legend(title="Log fold-change")) +
  theme(axis.line = element_line(colour = "black", size = 0.3),
        axis.ticks = element_line(colour = "black", size = 0.3),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        panel.border = element_blank(), 
        panel.background = element_blank(), 
        axis.title = element_text(size=6, face="bold"),
        axis.text = element_text(size=6, face="bold"),
        legend.text = element_text(size=6, face="bold"),
        legend.title = element_text(size=6, face="bold"),
        legend.key.height = unit(0.2, "cm"),
        legend.key.width = unit(0.4, "cm")) +
  xlab("UMAP 1") + ylab("UMAP 2") +
  scale_fill_gradient2(low = "#33CC66", mid = "white", high = "#336666")
  
milo.umap.glia.plot
```

# Figure 2f
```{r}
# Differential abundant neighborhoods across hippocampal cell populations
# Compute DA neighborhoods per cell type for glial cells (Veh-LPS vs. veh-PBS)
design <- data.frame(colData(hippo.glia.veh.milo))[, c("hash.ID", "drug", "time")]
design <- distinct(design)
design$drug <- factor(design$drug, levels = c("Veh-PBS", "Veh-LPS"))
rownames(design) <- design$hash.ID

model <- model.matrix(~ drug, data = design)
colnames(model) <- make.names(colnames(model))
da.results.glia.veh <- testNhoods(hippo.glia.veh.milo, design = model, design.df = design, model.contrasts = "drugVeh.LPS")

da.results.glia.veh <- annotateNhoods(hippo.glia.veh.milo, da.results.glia.veh, coldata_col = "cell.type")
da.results.glia.veh$cell.type <- ifelse(da.results.glia.veh$cell.type_fraction < 0.7, "Mixed", da.results.glia.veh$cell.type)

da.neighborhoods.glia.veh <- data.frame(matrix(NA, nrow = length(unique(da.results.glia.veh$cell.type)), ncol = 2))
colnames(da.neighborhoods.glia.veh) <- c("cell.type", "percent")
da.neighborhoods.glia.veh$cell.type <- unique(da.results.glia.veh$cell.type)

for (i in 1:nrow(da.neighborhoods.glia.veh)) {
  cell.type <- da.neighborhoods.glia.veh$cell.type[i]
  significant <- length(which(da.results.glia.veh$cell.type == cell.type & da.results.glia.veh$SpatialFDR < 0.05)) 
  all <- length(which(da.results.glia.veh$cell.type == cell.type)) 
  da.neighborhoods.glia.veh$percent[i] <- significant / all * 100
}

# Compute DA neighborhoods per cell type for glial cells (Sema-LPS vs. veh-LPS)
design <- data.frame(colData(hippo.glia.LPS.milo))[, c("hash.ID", "drug", "time")]
design <- distinct(design)
design$drug <- factor(design$drug, levels = c("Veh-LPS", "Sema-LPS"))
rownames(design) <- design$hash.ID

model <- model.matrix(~ drug, data = design)
colnames(model) <- make.names(colnames(model))
da.results.glia.LPS <- testNhoods(hippo.glia.LPS.milo, design = model, design.df = design, model.contrasts = "drugSema.LPS")

da.results.glia.LPS <- annotateNhoods(hippo.glia.LPS.milo, da.results.glia.LPS, coldata_col = "cell.type")
da.results.glia.LPS$cell.type <- ifelse(da.results.glia.LPS$cell.type_fraction < 0.7, "Mixed", da.results.glia.LPS$cell.type)

da.neighborhoods.glia.LPS <- data.frame(matrix(NA, nrow = length(unique(da.results.glia.LPS$cell.type)), ncol = 2))
colnames(da.neighborhoods.glia.LPS) <- c("cell.type", "percent")
da.neighborhoods.glia.LPS$cell.type <- unique(da.results.glia.LPS$cell.type)

for (i in 1:nrow(da.neighborhoods.glia.LPS)) {
  cell.type <- da.neighborhoods.glia.LPS$cell.type[i]
  significant <- length(which(da.results.glia.LPS$cell.type == cell.type & da.results.glia.LPS$SpatialFDR < 0.05)) 
  all <- length(which(da.results.glia.LPS$cell.type == cell.type)) 
  da.neighborhoods.glia.LPS$percent[i] <- significant / all * 100
}

# Compute DA neighborhoods per cell type for neurons (Veh-LPS vs. veh-PBS)
design <- data.frame(colData(hippo.neurons.veh.milo))[, c("hash.ID", "drug", "time")]
design <- distinct(design)
design$drug <- factor(design$drug, levels = c("Veh-PBS", "Veh-LPS"))
rownames(design) <- design$hash.ID

model <- model.matrix(~ drug, data = design)
colnames(model) <- make.names(colnames(model))
da.results.neurons.veh <- testNhoods(hippo.neurons.veh.milo, design = model, design.df = design, model.contrasts = "drugVeh.LPS")

da.results.neurons.veh <- annotateNhoods(hippo.neurons.veh.milo, da.results.neurons.veh, coldata_col = "cell.type")
da.results.neurons.veh$cell.type <- ifelse(da.results.neurons.veh$cell.type_fraction < 0.7, "Mixed", da.results.neurons.veh$cell.type)

da.neighborhoods.neurons.veh <- data.frame(matrix(NA, nrow = length(unique(da.results.neurons.veh$cell.type)), ncol = 2))
colnames(da.neighborhoods.neurons.veh) <- c("cell.type", "percent")
da.neighborhoods.neurons.veh$cell.type <- unique(da.results.neurons.veh$cell.type)

for (i in 1:nrow(da.neighborhoods.neurons.veh)) {
  cell.type <- da.neighborhoods.neurons.veh$cell.type[i]
  significant <- length(which(da.results.neurons.veh$cell.type == cell.type & da.results.neurons.veh$SpatialFDR < 0.05)) 
  all <- length(which(da.results.neurons.veh$cell.type == cell.type)) 
  da.neighborhoods.neurons.veh$percent[i] <- significant / all * 100
  
}

# Compute DA neighborhoods per cell type for neurons (Sema-LPS vs. veh-LPS)
design <- data.frame(colData(hippo.neurons.LPS.milo))[, c("hash.ID", "drug", "time")]
design <- distinct(design)
design$drug <- factor(design$drug, levels = c("Veh-LPS", "Sema-LPS"))
rownames(design) <- design$hash.ID

model <- model.matrix(~ drug, data = design)
colnames(model) <- make.names(colnames(model))
da.results.neurons.LPS <- testNhoods(hippo.neurons.LPS.milo, design = model, design.df = design, model.contrasts = "drugSema.LPS")

da.results.neurons.LPS <- annotateNhoods(hippo.neurons.LPS.milo, da.results.neurons.LPS, coldata_col = "cell.type")
da.results.neurons.LPS$cell.type <- ifelse(da.results.neurons.LPS$cell.type_fraction < 0.7, "Mixed", da.results.neurons.LPS$cell.type)

da.neighborhoods.neurons.LPS <- data.frame(matrix(NA, nrow = length(unique(da.results.neurons.LPS$cell.type)), ncol = 2))
colnames(da.neighborhoods.neurons.LPS) <- c("cell.type", "percent")
da.neighborhoods.neurons.LPS$cell.type <- unique(da.results.neurons.LPS$cell.type)

for (i in 1:nrow(da.neighborhoods.neurons.LPS)) {
  cell.type <- da.neighborhoods.neurons.LPS$cell.type[i]
  significant <- length(which(da.results.neurons.LPS$cell.type == cell.type & da.results.neurons.LPS$SpatialFDR < 0.05)) 
  all <- length(which(da.results.neurons.LPS$cell.type == cell.type)) 
  da.neighborhoods.neurons.LPS$percent[i] <- significant / all * 100
}


# Merge
da.neighborhoods.glia.veh$comparison <- "Veh-LPS vs. veh-PBS"
da.neighborhoods.glia.LPS$comparison <- "Sema-LPS vs. veh-LPS"
da.neighborhoods.neurons.veh$comparison <- "Veh-LPS vs. veh-PBS"
da.neighborhoods.neurons.LPS$comparison <- "Sema-LPS vs. veh-LPS"

da.neighborhoods <- rbind(da.neighborhoods.glia.veh, da.neighborhoods.glia.LPS,
                          da.neighborhoods.neurons.veh, da.neighborhoods.neurons.LPS)

da.neighborhoods$comparison <- factor(da.neighborhoods$comparison, levels = c("Veh-LPS vs. veh-PBS", "Sema-LPS vs. veh-LPS"))

da.neighborhoods <- da.neighborhoods[!(da.neighborhoods$cell.type == "Mixed"), ]
da.neighborhoods$cell.type <- factor(da.neighborhoods$cell.type,
                                     levels = c(levels(hippo.glia$cell.type2), sort(unique(hippo.neurons$cell.type2))))


da.neighborhoods[order(da.neighborhoods$percent, decreasing = T),]
```

```{r}
# Plot
DA.neighborhood.plot <- ggplot(da.neighborhoods, aes(x = cell.type, y = percent, fill = comparison)) +
  geom_bar(position = position_dodge(), stat="identity", colour="black", width=0.8, size=0.3) +
  theme_pubr(legend = "top") +
  theme(axis.line = element_line(colour = "black", size = 0.3),
        axis.ticks = element_line(colour = "black", size = 0.3),
        axis.text.y = element_text(size=6, face="bold"),
        axis.title = element_text(size=6, face="bold"),
        axis.text.x = element_text(size=6, face="bold", angle=45, hjust=1),
        legend.text = element_text(size=6, face="bold"),
        # margin: top, right, bottom, and left
        legend.margin=margin(0, 0, 0, 0),
        legend.box.margin=margin(0, 0, 0, 0),
        plot.margin = unit(c(0.1, 0, -0.25, 0.35), "cm"),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(),
        legend.key.height = unit(0.1, "cm"),
        legend.key.width = unit(0.2, "cm")) +
  xlab("") + ylab("DA neighborhoods (%)") +
  scale_fill_manual(values = c("#96C2D0", "#FC6A03")) 

DA.neighborhood.plot
```

# Figure 2g 
```{r}
# Neutrophil proportions
# Load data
neutrophils.prop.list <- readRDS("/projects/mludwig/hippo_GLP1/output/cacoa/hippo_neutrophils_prop_list.rds")
neutrophils.veh.loadings <- neutrophils.prop.list[["veh.loadings"]]
neutrophils.veh.p <- neutrophils.prop.list[["veh.p"]]
neutrophils.LPS.loadings <- neutrophils.prop.list[["LPS.loadings"]]
neutrophils.LPS.p <- neutrophils.prop.list[["LPS.p"]]

neutrophils <- as.data.frame(table(hippo.glia$hash.ID[which(hippo.glia$cell.type2 == "Neutrophils")]))
cells.all <- as.data.frame(table(hippo.glia$hash.ID))

prop.data <- merge(neutrophils, cells.all, by = "Var1")
colnames(prop.data) <- c("hash.ID", "freq.neutrophils", "freq.all")
prop.data$prop <- prop.data$freq.neutrophils / prop.data$freq.all * 100
prop.data$treatment <- gsub("-[0-9]+$", "", unique(prop.data$hash.ID))
prop.data$treatment <- factor(prop.data$treatment, levels = c("Veh-PBS-2h", "Veh-PBS-24h",
                                                               "Veh-LPS-2h", "Veh-LPS-24h",
                                                               "Veh-LPS-5d", "Veh-LPS-11d",
                                                               "Sema-LPS-2h", "Sema-LPS-24h",
                                                               "Sema-LPS-5d", "Sema-LPS-11d"))
prop.data$drug <- factor(gsub("-[0-9].*", "", prop.data$treatment),
                         levels = c("Veh-PBS", "Veh-LPS", "Sema-LPS"))
prop.data$time <- factor(gsub(".*-", "", prop.data$treatment),
                         levels = c("2h", "24h", "5d", "11d"))

neutrophils.LPS.p$comparison <- "sema-LPS vs. veh-LPS"
neutrophils.veh.p$comparison <- "veh-PBS vs. veh-LPS"

neutrophils.p <- rbind(neutrophils.LPS.p, neutrophils.veh.p)
neutrophils.p$p.adjust <- p.adjust(neutrophils.p$p.value, method = "fdr")
neutrophils.p$asterisk <- ""
neutrophils.p$asterisk[which(neutrophils.p$p.adjust <= 0.05 & neutrophils.p$p.adjust > 0.01)] <- "*"
neutrophils.p$asterisk[which(neutrophils.p$p.adjust <= 0.01 & neutrophils.p$p.adjust > 0.001)] <- "**"
neutrophils.p$asterisk[which(neutrophils.p$p.adjust <= 0.001)] <- "***"
neutrophils.p$position <- vector(mode = "numeric", length = nrow(neutrophils.p))
neutrophils.p$symbol <- round(neutrophils.p$p.adjust, digits = 3)
neutrophils.p$symbol <- ifelse(neutrophils.p$symbol <= 0.05, neutrophils.p$symbol, "NS")

for (i in 1:nrow(neutrophils.p)) {

  comparison <- neutrophils.p$comparison[i]
  time <- neutrophils.p$time[i]

  if (comparison == "LPS") {
    idx <- which(prop.data$drug %in% c("Sema-LPS", "Veh-LPS") & prop.data$time == time)
  }
  else {
    idx <- which(prop.data$drug %in% c("Sema-LPS", "Veh-LPS") & prop.data$time == time)

  }
  neutrophils.p$position[i] <- max(prop.data$prop[idx])
}

asterisk.position <- c()
for (i in unique(prop.data$treatment)) {
  asterisk.position <- c(asterisk.position,
                         max(prop.data$prop[which(prop.data$treatment == i)]))
}

# Plot
neutrophil.prop.plot <- ggplot(prop.data, aes(x = time, y = prop, fill = drug)) +
  geom_boxplot(notch = F, size = 0.3, outlier.shape = NA,
           position = position_dodge(0.6), width = 0.5) +
  theme_pubr() +
  theme(axis.line = element_line(colour = "black", size = 0.3),
        axis.ticks = element_line(colour = "black", size = 0.3),
        axis.text.x = element_text(size=6, face="bold", angle=45, hjust=1),
        axis.text.y = element_text(size=6, face="bold"),
        axis.title = element_text(size=6, face="bold"),
        legend.text = element_text(size=6, face="bold"),
        # margin: top, right, bottom, and left
        legend.margin=margin(0, 0, -5, 0),
        legend.box.margin=margin(0, 0, 0, 0),
        plot.margin = unit(c(0, 0, -0.25, 0), "cm"),
        legend.title = element_blank(),
        legend.key.height = unit(0.1, "cm"),
        legend.key.width = unit(0.2, "cm")) +
  ylab("Neutrophil proportion (%)") + xlab("") +
  scale_fill_manual(values = c("#33CC66", "#336666", "#A60FA6")) +
  geom_signif(y_position=c(0.5 + neutrophils.p$position[c(5, 1, 6, 2)]), xmin=c(0.8, 1.01, 1.8, 2.01),
              xmax=c(0.99, 1.2, 1.99, 2.2), tip_length = 0.02,
              fontface = "bold",
              annotation = neutrophils.p$symbol[c(5, 1, 6, 2)],
              size = 0.2, textsize = 1.55, parse = F, hjust = 0.4) +
  scale_y_continuous(limits = c(0, 8))
neutrophil.prop.plot
```


# Combine all plots
```{r}
plot1 <- plot_grid(umap.glia.plot + theme(plot.margin = unit(c(0, 0.2, 0, 0), "cm")), 
                   umap.neurons.plot + theme(plot.margin = unit(c(0, 0, 0, 0.2), "cm")), 
                   ncol = 2, align = "h", axis = "tb",                   
                   rel_widths = c(1, 1)) 

plot2 <- plot_grid(get_legend(milo.umap.glia.plot) ,
                   get_legend(DA.neighborhood.plot),
                   ncol = 2, align = "h", axis = "tb",                   
                   rel_widths = c(1, 1)) 

plot3 <- plot_grid(DA.neighborhood.plot + theme(legend.position = "none",
                                                plot.margin = unit(c(0, 0, 0.1, 0), "cm")), 
                   neutrophil.prop.plot + theme(plot.margin = unit(c(0.1, 0, 0, 0), "cm")), 
                   ncol = 1, align = "v", axis = "rl",                   
                   rel_heights = c(1, 1)) 

plot4 <- plot_grid(milo.umap.glia.plot + theme(legend.position = "none",
                                               plot.margin = unit(c(0, 0.2, 0, 0), "cm")), 
                   plot3 + theme(plot.margin = unit(c(0, 0, -0.18, 0.2), "cm")), 
                   ncol = 2, align = "h", axis = "t",                   
                   rel_widths = c(1, 1)) 

# Margin: top, right, bottom, and left
fig2 <- plot_grid(plot1 + theme(plot.margin = unit(c(0, 0, 0, 0), "cm")),
                  plot2, 
                  plot4 + theme(plot.margin = unit(c(0, 0, 0, 0), "cm")),
                  ncol = 1, align = "v",
                  rel_heights = c(1, 0.2, 1))

ggsave("/projects/mludwig/hippo_GLP1/output/figures/figure2.png", fig2, height = 170, width = 183,
       units = "mm")

```
